<a href="http://esprit.tn"><img src = "https://upload.wikimedia.org/wikipedia/commons/f/ff/Logo_ESPRIT_Ariana.jpg" width = 300, align = "center"></a>



<h1 align=center><font size = 5>Lab 9: Supervised learning -  Artificial Neural Networks (ANN) </font></h1>

Estimated duration: 90 min

## LAB 9: IDS BASED ON MACHINE LEARNING TECHNIQUES

## Goal

We aim through this lab to build a robust intrusion detection system (IDS) based on a set of machine learning techinques.
Various techniques will be explored and experimented to assess IDS robustness according to two criteria:
    - maximizing the number of atatcks  detected 
    - reducing the number of false positive alerts
The experiemtal study will cover the following methods:
    - ANN
    - Decision trees / random forest
    - SVM

## Part I: Data loading and preparation 

Load the data preprare columns for ANN as done in the mini_lab9

In [1]:
import numpy as np
import pandas as pnd
import sklearn as sk
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (precision_score, recall_score,f1_score, accuracy_score,mean_squared_error,mean_absolute_error)
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import Normalizer

from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import (precision_score, recall_score,f1_score, accuracy_score,mean_squared_error,mean_absolute_error, roc_curve, classification_report,auc)


In [2]:
import datetime
t=datetime.datetime.now()
print(datetime.datetime.now()- t)

def init_chrono():
    return datetime.datetime.now()

def elapsed_time(t):
    if t:
        delta = init_chrono() - t
        print ('Elapsed time', delta)
        return delta 
    
# test
t = init_chrono()
elapsed_time(t)

0:00:00.000040
Elapsed time 0:00:00.000029


datetime.timedelta(microseconds=29)

In [4]:
print(sk.__version__)

0.20.1


In [13]:
data_path = './'
traindata = pnd.read_csv(data_path+'train.csv', header=None)
testdata = pnd.read_csv(data_path+'test.csv', header=None)

print('train_data', traindata.shape, '\n', 'test_data:', testdata.shape)

train_data (494021, 42) 
 test_data: (311029, 42)


In [15]:
def show_dist(df_column, tag = 'Column'):
    if not df_column.empty: 
        dist = df_column.value_counts()
        print("%s distribution:\n" %tag, dist)
#Test
#show_dist(traindata[41], tag="train dataset before ")  


def get_categorical(dataframe):
    types = dataframe.dtypes
    i = 0
    lst_cat=[]
    for var in types:
        if var == 'object':
            print(i)
            lst_cat.append(i)
        i=i+1
    return lst_cat

def handle_categorical(dataframe):
    if type(dataframe) != pnd.DataFrame:
        return None 

    lst= get_categorical(dataframe)
    
    print('%d variables are categorical %s ' %(len(lst), lst))
    for var_cat in lst:
        try:
            enc = sk.preprocessing.label.LabelEncoder()
            tmp = dataframe
            dataframe[var_cat] = enc.fit_transform(dataframe[var_cat])
            try:
                show_dist(tmp[var_cat], 'Var[' + str(var_cat) + '] (before)')
                show_dist(dataframe[var_cat], 'Var[' + str(var_cat) + '] (after)')
            except NameError as nmE:
                print(nmE)
        except Exception as e:
            print('Exception: Unable to convert categorical variable ', var_cat, e)
            


In [16]:
traindata[41] = traindata[41].map(lambda x: 1 if x != 'normal.' else 0)
testdata[41] = testdata[41].map(lambda x: 1 if x != 'normal.' else 0)

# handling categorical data
handle_categorical(traindata)
handle_categorical(testdata)

# creating values and classes
x_train, y_train = traindata.iloc[:, :41], traindata.iloc[:, 41]
x_test, y_test = testdata.iloc[:, :41], testdata.iloc[:, 41]
# normalizing
scaler = Normalizer().fit(x_train)
trainX = scaler.transform(x_train)

scaler = Normalizer().fit(x_test)
testX = scaler.transform(x_test)


traindata = np.array(trainX)
trainlabel = np.array(y_train)

testdata = np.array(testX)
testlabel = np.array(y_test)

1
2
3
3 variables are categorical [1, 2, 3] 
Var[1] (before) distribution:
 0    283602
1    190065
2     20354
Name: 1, dtype: int64
Var[1] (after) distribution:
 0    283602
1    190065
2     20354
Name: 1, dtype: int64
Var[2] (before) distribution:
 14    281400
45    110893
22     64293
50      9723
40      7237
11      5863
19      4721
13      1642
18       798
17       670
61       538
56       513
39       380
3        328
43       202
59       157
6        126
47       120
20       117
24       117
10       116
9        116
55       115
25       115
49       112
12       112
48       111
65       110
51       110
44       109
       ...  
63       106
62       106
4        106
26       106
52       105
54       105
37       105
21       104
30       104
8        103
15       103
34       102
29       102
42       101
28       101
23        99
16        99
33        99
32        98
27        98
7         97
36        95
2         92
0         43
60        14
1         11
58    

# Part II: Neural networks 

1) Build 3 neural networks with respecitvely 2 hidden layers, one hidden layer, and a learning rate equal to .5

In [17]:
import sklearn.neural_network as nn

In [11]:
# first one
# print(nn.MLPClassifier.__doc__)
model1 = nn.MLPClassifier(activation='logistic',
                          hidden_layer_sizes=(2,),
                          max_iter=10,solver='sgd',
                          verbose=True,
                          learning_rate='constant',
                          learning_rate_init=.5)

In [18]:
model1.fit(traindata, trainlabel)

Iteration 1, loss = 0.04297154
Iteration 2, loss = 0.03081398
Iteration 3, loss = 0.02798865
Iteration 4, loss = 0.02645478
Iteration 5, loss = 0.02565081
Iteration 6, loss = 0.02515808
Iteration 7, loss = 0.02477040
Iteration 8, loss = 0.02439204
Iteration 9, loss = 0.02406671
Iteration 10, loss = 0.02376612


/home/aminos/esprit/4nids/decision/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='logistic', alpha=0.0001, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(2,), learning_rate='constant',
       learning_rate_init=0.5, max_iter=10, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='sgd', tol=0.0001,
       validation_fraction=0.1, verbose=True, warm_start=False)

In [20]:
# second model
model2 = nn.MLPClassifier(activation='logistic',
                         hidden_layer_sizes=(1,),
                         max_iter=10,
                         solver='sgd',
                         verbose=True,
                         learning_rate='constant',
                         learning_rate_init=.5)

In [21]:
model2.fit(traindata, trainlabel)

Iteration 1, loss = 0.04653822
Iteration 2, loss = 0.03683141
Iteration 3, loss = 0.03653846
Iteration 4, loss = 0.03651475
Iteration 5, loss = 0.03638192
Iteration 6, loss = 0.03616684
Iteration 7, loss = 0.03616427
Iteration 8, loss = 0.03620227
Iteration 9, loss = 0.03612422
Iteration 10, loss = 0.03612710


/home/aminos/esprit/4nids/decision/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='logistic', alpha=0.0001, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(1,), learning_rate='constant',
       learning_rate_init=0.5, max_iter=10, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='sgd', tol=0.0001,
       validation_fraction=0.1, verbose=True, warm_start=False)

In [22]:
model3 = nn.MLPClassifier(activation='logistic',
                         hidden_layer_sizes=(1,),
                         max_iter=10,
                         solver='sgd',
                         verbose=True)

In [23]:
model3.fit(traindata, trainlabel)

Iteration 1, loss = 0.53675236
Iteration 2, loss = 0.49483910
Iteration 3, loss = 0.49016344
Iteration 4, loss = 0.47071230
Iteration 5, loss = 0.41000609
Iteration 6, loss = 0.30996182
Iteration 7, loss = 0.22350157
Iteration 8, loss = 0.16783493
Iteration 9, loss = 0.13314749
Iteration 10, loss = 0.11076962


/home/aminos/esprit/4nids/decision/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='logistic', alpha=0.0001, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(1,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=10, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='sgd', tol=0.0001,
       validation_fraction=0.1, verbose=True, warm_start=False)

2) Compare accuracy performance of the obtained trained model and IDS assessment criteria: 
    (I) detected attacks, 
    (ii) false positive rate 


In [24]:
predicted1 = model1.predict(testdata)
predicted2 = model2.predict(testdata)
predicted3 = model3.predict(testdata)

In [25]:
def validation_KPIs(expected, predicted, avg='macro'):
    t = init_chrono()
    accuracy = accuracy_score(expected, predicted)
    recall = recall_score(expected, predicted, average=avg)
    precision = precision_score(expected, predicted , average=avg)
    f1 = f1_score(expected, predicted , average=avg)
    cm = metrics.confusion_matrix(expected, predicted)
    print('Confusion matrix:\n',cm)
    tpr = float(cm[0][0])/np.sum(cm[0])
    fpr = float(cm[1][1])/np.sum(cm[1])
    print("Accuracy 0_class: %.3f" %tpr)
    print("Accuracy 1_class: %.3f" %fpr)
    print("Accuracy: %.3f" %accuracy)
    print("Precision: %.3f" %precision)
    print("Recall: %.3f" %recall)
    print("F1_score: %.3f" %f1)

    print("***************************************************************")
    elapsed_time(t)
    return cm

In [27]:
validation_KPIs(testlabel, predicted1)

Confusion matrix:
 [[ 58976   1617]
 [ 56374 194062]]
Accuracy 0_class: 0.973
Accuracy 1_class: 0.775
Accuracy: 0.814
Precision: 0.752
Recall: 0.874
F1_score: 0.770
***************************************************************
Elapsed time 0:00:00.434618


array([[ 58976,   1617],
       [ 56374, 194062]])

In [29]:
validation_KPIs(testlabel, predicted2)

Confusion matrix:
 [[ 59088   1505]
 [ 57119 193317]]
Accuracy 0_class: 0.975
Accuracy 1_class: 0.772
Accuracy: 0.812
Precision: 0.750
Recall: 0.874
F1_score: 0.768
***************************************************************
Elapsed time 0:00:00.415717


array([[ 59088,   1505],
       [ 57119, 193317]])

In [28]:
validation_KPIs(testlabel, predicted3)

Confusion matrix:
 [[ 56934   3659]
 [ 18318 232118]]
Accuracy 0_class: 0.940
Accuracy 1_class: 0.927
Accuracy: 0.929
Precision: 0.871
Recall: 0.933
F1_score: 0.897
***************************************************************
Elapsed time 0:00:00.410534


array([[ 56934,   3659],
       [ 18318, 232118]])

## Part III:  Decision trees

1) Build a decision tree for a binary classification problem.


2) Compare false positives to best model obtained with neural net resuults

In [8]:
model4_tree = DecisionTreeClassifier()

## Part IV: Support Vector Machines 

1)-Build an Ids based on  2 svm by selecting the more accurate one: 
    (1)  SVM with a linear kernel 
    (2)  SVM with an rbf kernel an rbf svm kernel.


2)-  Compare the accuracy of svm models, ANN and decision tree


3)- Comapre computaional cost


4)- Can you find a tradeoff between accuracy and training cost and select the best model?

 <hr>
Copyright &copy; Nov-2018 Dr.Amir Esseghir